import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.min.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <section style={{ marginBottom: '0px' }}>
          <Link href="/"><button id="nav" > الصفحه الرئيسيه</button> </Link>
          <h1>أذكار</h1>
          <Link href="/contact"><button id="nav">تواصل معنا</button></Link>
        </section>
        {children}
      </body>
    </html>
  );
}
